### ISSUE TITLE
Collection title out of container

### ISSUE THREAD

**Issue by adler99** [luciddesign/bootstrapify#215]
Title of collection appears on the very left side of view port. It should be within the container limits.
I guess it is because in collection-page.liquid the collection-header is included before the container-open includes.
Cool template! Thanks for the good work!

**Comment by adler99** [comment]
Sorry stewartknapman, but my template is modified in many places, I can not install the new version and check if its locking all right... how do you test that stuff? Having an extra shopify account for testing?

**Comment by stewartknapman** [comment]
@adler99 we are Shopify partners (http://www.shopify.com/partners) so we have access to create as many development stores as we need for working with. If you're working with Shopify a lot then I suggest you sign up to be a partner.

Also as far as upgrading the theme goes, you should just be able to do a `git pull`. You might end up with some conflicts, but they should be easy enough to work through. That way you'll get the benefit of bug fixes, etc.
