### ISSUE TITLE
Warning: EMFILE, too many open files

### ISSUE THREAD

**Issue by cruelmelody** [luciddesign/bootstrapify#232]
Hey guys,

Really great work on this project, firstly. I'm just having some issues when running 'grunt watch'. As far as my installation goes, I've executed the project setup by the books. When it comes time to run 'grunt watch', the watch task goes into a repetitive loop, won't compile, and spits out the following:

`Warning: EMFILE, too many open files`

Has anybody else ran into this issue? I'd like to resolve it so I can compile my files.

Cheers.

**Comment by stewartknapman** [comment]
@cruelmelody I've not come across this before so I'm not really sure what's happening here. I did a quick search and found this though: https://github.com/gruntjs/grunt-contrib-copy/issues/21#issuecomment-46194402 Does that help at all?

**Comment by cruelmelody** [comment]
@stewartknapman Thanks for getting back to me. I tried that but had no such luck in resolving the issue with my existing project. I might try and set up the workflow from scratch again and work through each step methodically - I may have missed a crucial step in the project setup. I'll let you know how it goes.

**Comment by cruelmelody** [comment]
@stewartknapman I still have zero clue as to why this bug was occurring, but after a fresh install and updating all project dependencies, everything is compiling fine now.

**Comment by stewartknapman** [comment]
@cruelmelody Ok cool. Glad you've got it sorted.

Like I said, I've not come across it before, but i'll keep my eye out. Thanks.
